"""empty message

Revision ID: 2e2d31aeac6b
Revises: baf0a20e7550
Create Date: 2019-06-12 16:13:56.736005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e2d31aeac6b'
down_revision = 'baf0a20e7550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testline', 'control_pc_ip',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('testline', 'enb_position',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('testline', 'hw_infor',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('testline', 'pc_account',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('testline', 'pc_pwd',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('testline', 'user_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testline', 'user_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('testline', 'pc_pwd',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('testline', 'pc_account',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('testline', 'hw_infor',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('testline', 'enb_position',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('testline', 'control_pc_ip',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
