"""empty message

Revision ID: baf0a20e7550
Revises: f4e003c48275
Create Date: 2019-06-12 15:51:41.405190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf0a20e7550'
down_revision = 'f4e003c48275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testline', sa.Column('hw_infor', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testline', 'hw_infor')
    # ### end Alembic commands ###
