"""empty message

Revision ID: f4e003c48275
Revises: 
Create Date: 2019-06-06 15:23:36.549663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e003c48275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_line_name', sa.String(length=50), nullable=False),
    sa.Column('owner_name', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('control_pc_ip', sa.String(length=20), nullable=False),
    sa.Column('pc_account', sa.String(length=20), nullable=False),
    sa.Column('pc_pwd', sa.String(length=50), nullable=False),
    sa.Column('mplane_ip', sa.String(length=20), nullable=False),
    sa.Column('bts_id', sa.String(length=20), nullable=False),
    sa.Column('enb_position', sa.String(length=20), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=20), nullable=False),
    sa.Column('module_sn', sa.String(length=20), nullable=False),
    sa.Column('module_product_code', sa.String(length=20), nullable=False),
    sa.Column('module_position', sa.String(length=20), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('test_line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_line_id'], ['testline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module')
    op.drop_table('testline')
    # ### end Alembic commands ###
